### ISSUE TITLE
RuntimeError: Unconvertible NCCL type

### ISSUE THREAD

**Issue by suntaochun** [MAZiqing/FEDformer#10]
Hello Colleagues,

I just try to use FEDformer to run some LSTP tasks, and I directly use your default configurations in the run.py.  

--------------------**First Question (Multi-GPU usage)**------------------------

But the RuntimeError shows **Unconvertible NCCL type** when the model uses the nn.DataParallel to parallelize. Have you ever encountered such issues when conducting experiments before? Thanks for your possible suggestions and help.

By the way, I use the **Pytorch Version 1.5** and previously **have used the Autoformer to conduct the same tasks but didn't receive similar errors from Pytorch**. The difference between those is using the Frontier Transform (parser's default is to use Frontier) to decompose the time series. 

In your codes implementing the Frontier module in the layers/FrontierCorrelation.py, the param **modes** seems to control the Frontier based configs, I don't know whether some ops between the modes and the length of the sequence denoted as **seq_len** will affect the training. However, I have modified the value of **modes** to less than **seq_len** to satisfy the **index = index[:modes]** line in your codes, but the errors still exist.

--------------------**Second Question (Complex Multiplication)**--------------------

I try to directly update the Pytorch to v1.9 and now I can use multiple GPUs to train. So the first question may be solved by updating due to incompatibility. However, I find another problem occurs in the complex multiplication op (see the attached figure) and the errors show **einsum() the number of subscripts in the equation (3) does not match the number of dimensions (4) for operand 1 and no ellipsis was given** (see the attached figure). It's noted that **this time I entirely use your raw codes and the problems also exist**, so maybe some issues indeed need to be solved. 

You can directly email stc20@mails.tsinghua.edu.cn and look forward to your reply! 

In your paper, you said this model could outperform Autoformer and Transformer-based variants by almost 20%, so I would like to kindly ask about some issues and hope I can use this in my research later on.

Best

***Attached figures:***
![image](https://user-images.githubusercontent.com/31800139/176669828-d20ac004-7449-4917-9206-f7beadd4e553.png)
shows the Pytorch backend uses the **nn.DataParallel** to run on multiple GPUs.
![image](https://user-images.githubusercontent.com/31800139/176670093-63550f17-adf3-486d-97bd-6cc51ecdea36.png)
if the comm.py means *communications among processes*, there may be some errors in this part. But the Autoformer doesn't have this issue, so maybe it's because of the Frontier part? But this may be also a compatibility issue, so if you think it's worth discussing we can solve this issue by discussing in the email since you also just open-sourced the codes days before. It can benefit the entire community maybe.
![image](https://user-images.githubusercontent.com/31800139/176705789-2a71e6b7-648c-4300-8c9d-a2b74133ac53.png)
![image](https://user-images.githubusercontent.com/31800139/176706293-ba046abc-e825-4cdd-8211-951bc09aa42c.png)
complex multiplication issue

**Comment by tianzhou2011** [comment]
try to upgrade to PyTorch 1.9.0 at least, I am not sure about this NCCL type error.....

**Comment by suntaochun** [comment]
> 

Do you know the second question: the einsum issue? I think this is not the NCCL type error. After upgrading to 1.8, the NCCL type issue has been solved.

**Comment by tianzhou2011** [comment]
check my reply， i said upgrade to torch 1.9.0 at least not 1.8………

发自我的iPhone

**Comment by hsuxiang** [comment]
> > 
> 
> Do you know the second question: the einsum issue? I think this is not the NCCL type error. After upgrading to 1.8, the NCCL type issue has been solved.

hi~你解决了einsum这个问题了吗？ 我用的源码出现了一模一样的错误RuntimeError: einsum(): the number of subscripts in the equation (3) does not match the number of dimensions (4) for operand 1 and no ellipsis was given。太困惑了，能跟你讨论一下吗？求赐教

**Comment by hsuxiang** [comment]
> > 
> 
> Do you know the second question: the einsum issue? I think this is not the NCCL type error. After upgrading to 1.8, the NCCL type issue has been solved.

hi~你解决了einsum这个问题了吗？ 我用的源码出现了一模一样的错误RuntimeError: einsum(): the number of subscripts in the equation (3) does not match the number of dimensions (4) for operand 1 and no ellipsis was given。太困惑了，能跟你讨论一下吗？求赐教

**Comment by hsuxiang** [comment]
> check my reply， i said upgrade to torch 1.9.0 at least not 1.8……… 发自我的iPhone
> […](#)
> 在 2022年7月10日，03:07，Taochun Sun ***@***.***> 写道： ﻿ Do you know the second question: the einsum issue? I think this is not the NCCL type error. After upgrading to 1.8, the NCCL type issue has been solved. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.

Hello Colleagues, my torch version is 1.9.0, but this error will be reported when using multi gpu, as shown in the attached picture. I would like to ask the author if you have tried to run multiple Gpus, or do you have any suggestions to solve it? thank you for your kind reply.

**Comment by hsuxiang** [comment]
![image](https://user-images.githubusercontent.com/77951517/204738710-28e0301f-6334-49d5-bbde-8ddeb499b3f9.png)
Hello Colleagues, my torch version is 1.9.0, but this error will be reported when using multi gpu, as shown in the attached picture. I would like to ask the author if you have tried to run multiple Gpus, or do you have any suggestions to solve it? thank you for your kind reply.

**Comment by tianzhou2011** [comment]
You don't need to run a multi-GPU setting here. we never use that in all of
our experiments, the speed is reasonably fast. I would rewrite the project
using Pytorch lightning if I want to use multiple GPUs in the future. A lot
of things could go wrong with a hand-implemented one.
