### ISSUE TITLE
Run time error, ModuleNotFoundError: No module named 'utils.timefeatures'

### ISSUE THREAD

**Issue by wmmxk** [MAZiqing/FEDformer#11]
I was running the script and run into the above  error, although I add the absolute path (the parent directory of the utils folder) to my python path using sys.path.insert(0, <the absolute path>). I also tried creating a __init__.py file in the project directory, still it does not work.

Usually it should work so I run out of ideas.  Any ideas?

**Comment by tianzhou2011** [comment]
just google  "ModuleNotFoundError: No module named" and you can find a lot
of solutions for such problem.
