### ISSUE TITLE
touch.einsum malfunctioning issue

### ISSUE THREAD

**Issue by suntaochun** [MAZiqing/FEDformer#12]
Hello colleagues,

         Following this closed issue: https://github.com/MAZiqing/FEDformer/issues/10

         Do you have any suggestions on solving the torch.einsum tracebacks?

         Appreciate if I can receive a reply. I suppose torch.fft modules be not changed since 1.8, so that will not be the reason.

Best

**Comment by tianzhou2011** [comment]
read the readme page first.... upgrade torch to 1.9.0 as shown in the Readme
