### ISSUE TITLE
Can't use gpu

### ISSUE THREAD

**Issue by micah35s** [MAZiqing/FEDformer#13]
I have gpu and torch.cuda.is_available() True
![image](https://user-images.githubusercontent.com/18494091/178440771-88bdbb06-b29e-4ec9-80a5-4d6f55bd966b.png)

I just use run_M.sh and the training did not use GPU.

**Comment by RobinWenqian** [comment]
I successfully use GPU
There is another issue and I don't know what it is
![image](https://user-images.githubusercontent.com/18494091/178445857-a40a752f-1425-4b06-943d-85e92458910e.png)

**Comment by tianzhou2011** [comment]
read the readme please， my guess，your torch version is wrong

**Comment by RobinWenqian** [comment]
I found the solution. On Windows we need to put code of run.py under if __name__ == "__main__"

Wenqian (Bradley) He

Bachelor: Shanghai Jiao Tong University
Master: the University of Edinburgh

Company: ProbQuant (based in Shanghai)


________________________________
发件人: tianzhou2011 ***@***.***>
发送时间: Tuesday, July 12, 2022 5:34:19 PM
收件人: MAZiqing/FEDformer ***@***.***>
抄送: He Wenqian_Vincent ***@***.***>; Author ***@***.***>
主题: Re: [MAZiqing/FEDformer] Can't use gpu (Issue #13)


read the readme please， my guess，your torch version is wrong

**Comment by tianzhou2011** [comment]
great!
