### ISSUE TITLE
About MOE module

### ISSUE THREAD

**Issue by Zero-coder** [MAZiqing/FEDformer#14]
First,thanks for such great work.
I have a  little question about the MOE module,could you please simply explain how MOE work theoretically,or give me some literature that I can read,thanks.

**Comment by tianzhou2011** [comment]
Just goolge Mixture of experts, you should be able to find tones of papers.... Hinton's "Outrageously Large Neural Networks: The Sparsely-Gated Mixture-of-Experts Layer" is one of them.
