### ISSUE TITLE
about fourier self attention and fourier cross attention

### ISSUE THREAD

**Issue by AzureLeon1** [MAZiqing/FEDformer#16]
Thanks for this great work, but I have a little question about FourierBlock and FourierCrossAttention implemented in code:

you first call `torch.permute()` on qkv tensor to put the time dimension in the last dimension (Line 52, Line 95~97 in `FourierCorrelation.py`), and then conduct `fft()`, `einsum()` and `rfft()`. Then, you don't seem to swap the order of the dimensions back and call `torch.view()` (Line 221 in `AutoCorrelation.py`) directly to change the shape of the tensor from `(B, H, E, L)` to `(B, L, -1)`. Is that right?

**Comment by tianzhou2011** [comment]
Permuting it back and then reshaping seems to be better, it might even improve the result.  Sadly, we didn't notice at the time.
