### ISSUE TITLE
about zero-padding operation for the result of inverse Fourier transform

### ISSUE THREAD

**Issue by AzureLeon1** [MAZiqing/FEDformer#17]
Thanks for this great work, but I still have a question about zero-padding operation for the result of inverse Fourier transform:

In your code, you seem to adopt different padding patterns in fourier self-attention and fourier cross-attention. 
- In fourier self-attention (FourierBlock), you use the **key** of index dict to fill the out_ft, and make the rest part as zero-padding.  
- In fourier cross-attention (FourierCrossAttention), you use the **value** of index dict to fill the out_ft.

self-attention:
![image](https://user-images.githubusercontent.com/33917543/180630293-13920646-45f8-449d-8aa1-b9a0d43be171.png)

cross-attention:
![image](https://user-images.githubusercontent.com/33917543/180630312-4fcc7133-bdda-4055-8afe-4bc3e8317c44.png)

This is inconsistent.

**Comment by tianzhou2011** [comment]
Thank you for pointing it out, the above one should be out_ft[:,:,:,i], it is consistent under Lowest mode, while inconsistent under Random mode. we noticed that after running all the experiments and submitting the final version paper. We left it here unchanged as it should consistent with the experiments we did, but you can change it to improve the results.
