### ISSUE TITLE
FEA-f Structure - Different Implementation

### ISSUE THREAD

**Issue by omerlux** [MAZiqing/FEDformer#18]
Hey, thank you for this great study!

I have a question about the structure of FEA-f which you mentioned in the paper.
You mentioned that after achieving the scores from the activation function and Q_tild, K_tild we need to multiply it by the V_tild. But actually, in the code, there is no use in V at all and the multiplication is with V_tild which we already used.
So why is the change or/and what is the idea behind using the keys as values?

Thank you!

https://github.com/MAZiqing/FEDformer/blob/306add595141d262f02570b0150b5f9c2fbad0de/layers/FourierCorrelation.py#L118

**Comment by tianzhou2011** [comment]
We used the same learnable weight here for K and V, it helps stabilize the training a little bit, you can use xv_ft_ here as you noticed; it might give better results with careful tuning.
