### ISSUE TITLE
FEDformer/layers/FourierCorrelation.py中感觉qkv相乘有误，望解答

### ISSUE THREAD

**Issue by taoxuewen** [MAZiqing/FEDformer#19]
[FEDformer](https://github.com/MAZiqing/FEDformer)/[layers](https://github.com/MAZiqing/FEDformer/tree/master/layers)/FourierCorrelation.py
中的118行
xqkv_ft = torch.einsum("bhxy,bhey->bhex", xqk_ft, xk_ft_)
xk_ft_ 是否应该是xv？

**Comment by tianzhou2011** [comment]
issue里好几位问过，这里我们当时跑实验K,V用的相同的learnable
weight，可以提高一点训练的稳定性，后面忘记改回去了，文章表里的数据都是用这个设定相同的weight跑的，为了保持代码复现性就没改。你可以用不同的weight试试，或许能跑出比原文更好的结果
