### ISSUE TITLE
--features='S'

### ISSUE THREAD

**Issue by gensuineixin** [MAZiqing/FEDformer#21]
When I change the param '--features=' ,from 'M' to 'S',follow error return:
RuntimeError: Given groups=1, weight of size [512, 7, 3], expected input[32, 1, 98] to have 7 channels, but got 1 channels instead

**Comment by tianzhou2011** [comment]
you have to be more specific. what's the full command you are running?

**Comment by gensuineixin** [comment]
The other params are same in the file run.py.

**Comment by gensuineixin** [comment]
Args in experiment:
Namespace(L=3, activation='gelu', base='legendre', batch_size=32, c_out=7, checkpoints='./checkpoints/', cross_activation='tanh', d_ff=2048, d_layers=1, d_model=512, data='ETTh1', data_path='ETTh1.csv', dec_in=7, des='test', devices='0,1', distil=True, do_predict=False, dropout=0.05, e_layers=2, embed='timeF', enc_in=7, factor=1, features='S', freq='h', gpu=0, is_training=1, itr=3, label_len=48, learning_rate=0.0001, loss='mse', lradj='type1', mode_select='random', model='FEDformer', modes=64, moving_avg=[24], n_heads=8, num_workers=0, output_attention=False, patience=3, pred_len=96, root_path='./dataset/ETT/', seq_len=96, target='OT', task_id='test', train_epochs=10, use_amp=False, use_gpu=False, use_multi_gpu=False, version='Fourier')
Use CPU

**Comment by tianzhou2011** [comment]
you can't just change the features from M to S to run the univariate experiments. Run the scripts:run_S.sh. There are other changed parameters.
