### ISSUE TITLE
params:freq='15min'

### ISSUE THREAD

**Issue by gensuineixin** [MAZiqing/FEDformer#24]
Thanks for your great work and attention.
The Error is:
when I run the run.py,use params "--freq"= '15min',Then:

**File ".\FEDformer-master-min\layers\Embed.py", line 99, in __init__
    d_inp = freq_map[freq]
KeyError: '15min'**

and The Q is How to use '--freq' param with the value: '5min' or '15min'?

**Comment by gensuineixin** [comment]
and the params are:
Namespace(L=3, activation='relu', base='legendre', batch_size=32, c_out=1, checkpoints='./checkpoints/', cross_activation='softmax', d_ff=2048, d_layers=1, d_model=512, data='ETTm1', data_path='***', dec_in=1, des='Exp', devices='0,1', distil=True, do_predict=True, dropout=0.05, e_layers=2, embed='timeF', enc_in=1, factor=3, features='S', freq='15min', gpu=0, is_training=1, itr=1, label_len=48, learning_rate=0.0001, loss='mse', lradj='type1', mode_select='random', model='FEDformer', modes=64, moving_avg=[24], n_heads=8, num_workers=0, output_attention=False, patience=3, pred_len=360, root_path='./dataset/ETT/', seq_len=96, target='flow', task_id='test', train_epochs=1, use_amp=False, use_gpu=False, use_multi_gpu=False, version='Fourier')

**Comment by tianzhou2011** [comment]
We haven't implemented this feature. It's saved for potential future work.
Sorry, you can't use 15min or 5 min with the current code.
