### ISSUE TITLE
复现指标与论文中不一致

### ISSUE THREAD

**Issue by fourierer** [MAZiqing/FEDformer#29]
作者您好，感谢您的开源。
    我在复现论文Table 2时和表中的结果有一些差别，具体是在ECL数据集上跑了以下两个实验：
（1）使用run_S.sh跑了FEDformer，预测长度设置为96，其余参数设置和实验结果如下，略优于论文中的MSE:0.253; MAE:0.370；
![截屏2022-09-13 10 17 50](https://user-images.githubusercontent.com/55837279/189793063-cab2f754-bba2-478b-b0db-b18e98df818c.png)
![截屏2022-09-13 10 18 30](https://user-images.githubusercontent.com/55837279/189793228-abf1c410-b5ca-4949-b502-56e228951c64.png)

（2）使用run_M.sh跑了Informer，预测长度设置为96，其余参数设置和实验结果如下，比论文中的MSE:0.274; MAE:0.368要差；
![截屏2022-09-13 10 20 38](https://user-images.githubusercontent.com/55837279/189793545-9aa0460d-d0c8-4ab1-9840-b8b18e5d909c.png)
![截屏2022-09-13 10 20 09](https://user-images.githubusercontent.com/55837279/189793561-e8d31089-113d-4474-8994-fbe342bfb662.png)

请问以上的实验结果是在正常的波动范围内么，还是我有哪些地方疏忽了，感谢您的回复。

**Comment by tianzhou2011** [comment]
你好，fedformer的还算正常吧，确实我们没有grid search非常精细调参，跑出比report结果更好的是正常的。Informer的结果我们是引用得autoformer文章里的结果，其实没有都重新跑过。不过有些模型，波动性确实是大的，也算正常吧……

发自我的iPhone

**Comment by fourierer** [comment]
好的，感谢回复！

**Comment by fourierer** [comment]
关于table3中单变量预测的结果，Informer和Autoformer文章中单变量的预测实验结果不多，请问剩下的那些结果是在FEDformer中重新训练的么？还是所有的都是在FEDformer中重新训练的呀？
