### ISSUE TITLE
Error in shell script

### ISSUE THREAD

**Issue by chiyuzhang94** [MAZiqing/FEDformer#30]
I found the value of "features" in `run_M.sh` is "S", such as Lines: 
https://github.com/MAZiqing/FEDformer/blob/306add595141d262f02570b0150b5f9c2fbad0de/scripts/run_M.sh#L128
https://github.com/MAZiqing/FEDformer/blob/306add595141d262f02570b0150b5f9c2fbad0de/scripts/run_M.sh#L149
https://github.com/MAZiqing/FEDformer/blob/306add595141d262f02570b0150b5f9c2fbad0de/scripts/run_M.sh#L171

Are these typos?

**Comment by tianzhou2011** [comment]
Yes..... They are typos most likely, thank you for pointing them out==

**Comment by chiyuzhang94** [comment]
> Yes..... They are typos most likely, thank you for pointing them out==

Ok. Thanks for clarifying!
