### ISSUE TITLE
关于feature='MS'

### ISSUE THREAD

**Issue by shamoaaa** [MAZiqing/FEDformer#31]
您好，感谢您的开源。

我在使用feature=‘MS’模型跑exchange时发现输出维度是8维的，而且loss值很大。

![K%7IY5`_9 5MA58QL}WPV9](https://user-images.githubusercontent.com/91960797/191451058-2fda92a0-d680-4713-83fe-5857e9cb93bc.png)
![3}{GY09X)O38UL08%XC1JPL](https://user-images.githubusercontent.com/91960797/191451184-bcc4ce3b-e40d-4820-a117-694791aaeb10.png)

**Comment by tianzhou2011** [comment]
我们并没有跑过MS的任务，现在代码跑MS是有问题的。要跑MS任务，需要改一下代码，现在decoder trend固定成了feature的dimension 
![image](https://user-images.githubusercontent.com/7770939/191465685-d2b8ca2e-914e-4417-a808-260f0f7c7508.png)
你这要改一下，把MS时候喂进去的init value 和mean改成1维的

**Comment by FAFUuser** [comment]
> 您好，感谢您的开源。
> 
> 我在使用feature=‘MS’模型跑exchange时发现输出维度是8维的，而且loss值很大。
> 
> ![K%7IY5`_9 5MA58QL}WPV9](https://user-images.githubusercontent.com/91960797/191451058-2fda92a0-d680-4713-83fe-5857e9cb93bc.png) ![3}{GY09X)O38UL08%XC1JPL](https://user-images.githubusercontent.com/91960797/191451184-bcc4ce3b-e40d-4820-a117-694791aaeb10.png)

您好，请问MS的任务你实现了吗？如果实现了，代码具体是怎么修改可以学习一下吗？ 同时再向您请教一个问题，就是与S任务相比，针对于同一个OT，MS会对模型的精度有所提高吗？

**Comment by FAFUuser** [comment]
> 我们并没有跑过MS的任务，现在代码跑MS是有问题的。要跑MS任务，需要改一下代码，现在decoder trend固定成了feature的dimension ![image](https://user-images.githubusercontent.com/7770939/191465685-d2b8ca2e-914e-4417-a808-260f0f7c7508.png) 你这要改一下，把MS时候喂进去的init value 和mean改成1维的

您好，可以请教一下具体该怎么修改吗？非常感谢。

**Comment by lianqi1998** [comment]
也就是说现在的代码使用MS相当于使用M进行预测，然后取出预测结果的指定列？

> > 您好，感谢您的开源。
> > 我在使用feature=‘MS’模型跑exchange时发现输出维度是8维的，而且loss值很大。
> > ![K%7IY5`_9 5MA58QL}WPV9](https://user-images.githubusercontent.com/91960797/191451058-2fda92a0-d680-4713-83fe-5857e9cb93bc.png) ![3}{GY09X)O38UL08%XC1JPL](https://user-images.githubusercontent.com/91960797/191451184-bcc4ce3b-e40d-4820-a117-694791aaeb10.png)
> 
> 您好，请问MS的任务你实现了吗？如果实现了，代码具体是怎么修改可以学习一下吗？ 同时再向您请教一个问题，就是与S任务相比，针对于同一个OT，MS会对模型的精度有所提高吗？
