### ISSUE TITLE
Reproduce results for FEDformer with wavelet 

### ISSUE THREAD

**Issue by camerons1967** [MAZiqing/FEDformer#32]
Hello,
I tried to reproduce the results of the paper with the mwt block on the traffic data set but was unable to do so. I ran the code with the following args set:
<img width="277" alt="Screen Shot 2022-10-24 at 3 35 20 PM" src="https://user-images.githubusercontent.com/71870987/197526876-c5030657-7f3e-4d38-b211-4b0acfddc771.png">
with the addition of "--version Wavelets" and changing the "--features" from S to M. However, the model MSE score reached only about 0.585 after even more than three epochs versus the 0.562 MSE score that was reported in the paper for prediction length of 96. 
Are there any other parameters that need to be changed in order to reproduce the performance reported in the paper when using the wavelets? 
Thanks in advance!

**Comment by tianzhou2011** [comment]
Turn on the MOE decomposed block will improve the performance. We turn off
it by default to speed up the calculation.
[image: image.png]

**Comment by tianzhou2011** [comment]
![image](https://user-images.githubusercontent.com/7770939/197715972-f226cafe-3e25-4bf3-9733-33b4af61e71f.png)
