### ISSUE TITLE
requirements.txt is flawed

### ISSUE THREAD

**Issue by JustusMzB** [MAZiqing/FEDformer#33]
Hello there, first of all, thanks for the great repository.

I have noticed that with python 3.6 (as named in your prerequisites), installing the requirements with `python3 -m pip install -r requirements.txt` does not work for multiple reasons:

pytorch-wavelets is a non-existent package, the package is called pytorch-wavelet
pandas==1.4.2 requires python>=3.8

**Comment by tianzhou2011** [comment]
Thank you for pointing that out.  It might be running under python3.6 with
lower version of pandas as well, but since i am using python 3.8.x, Let me
correct those .....
Tian
