### ISSUE TITLE
FourierCorrelation problem

### ISSUE THREAD

**Issue by SiwGuan** [MAZiqing/FEDformer#34]
Thank you very much for making the code public. On line 119 of FourierCorrelation.py, I have a question.
`xqkv_ft = torch.einsum("bhxy,bhey->bhex", xqk_ft, xk_ft_)`
Why is the last parameter xk_ft_ the Fourier coefficient of key and not the Fourier coefficient of value?

**Comment by tianzhou2011** [comment]
#19  you can refer to issue 19, briefly, yes, it should be the coefficient of value. But we did all the experiment using this implementation, we kept it here. You can change it to xv_ft_, it might give you better results.
