### ISSUE TITLE
 About time complexity O(n)

### ISSUE THREAD

**Issue by Zero-coder** [MAZiqing/FEDformer#4]
First of all, thank you for such an excellent study.
The results of the Fedformer are awe-inspiring and insightful.

My question is how to understanding this time complexity,could you please talk about it:
When we choose the mode index before DFT and reverse DFT operations, the computation complexity can be further reduced to O(N ).

**Comment by tianzhou2011** [comment]
It means random discrete Fourier transformation, 
![image](https://user-images.githubusercontent.com/7770939/172783187-5595f690-399e-44bc-85b2-2b2f1fc9a1ed.png)
You can preselect k item from the overall n items and ignore the rest to save calculation

**Comment by Zero-coder** [comment]
Oh,I see,thanks for the response.
