### ISSUE TITLE
About environment requirements

### ISSUE THREAD

**Issue by serika-onoe** [MAZiqing/FEDformer#41]
I have noticed that when I try to reproduce the code, it popped out two error messages while I was under the environment the same as **Informer**'s:
```
ModuleNotFoundError: No module named 'einops'
```
and
```
ModuleNotFoundError: No module named 'sympy'
```
Then I found **it could be solved** by using these codes as follows
```
pip install einops
```
and
```
pip install sympy
```

**Comment by tianzhou2011** [comment]
Thanks, Let me add those two in the requirements.txt
