### ISSUE TITLE
running stuck 

### ISSUE THREAD

**Issue by guetaro** [MAZiqing/FEDformer#42]
Hi,

Nice work, thanks for shearing.

I have a problem while using the git, when running train using bash ./scripts/run_M.sh, the running stuck after printing:

train 34369
val 11425
test 11425

and remains stuck until I stop it myself.

I tried to debug it and found out the stuck happens on exp_main.py , after the command iter_count += 1.

do you have an idea why does it happen?

thanks in advance,

Roi

**Comment by tianzhou2011** [comment]
I am not sure what happened in your case. "Stuck" could be anything...Perhaps some other programs are occupying the CPU.

**Comment by jayyounghappy** [comment]
> Hi,
> 
> Nice work, thanks for shearing.
> 
> I have a problem while using the git, when running train using bash ./scripts/run_M.sh, the running stuck after printing:
> 
> train 34369 val 11425 test 11425
> 
> and remains stuck until I stop it myself.
> 
> I tried to debug it and found out the stuck happens on exp_main.py , after the command iter_count += 1.
> 
> do you have an idea why does it happen?
> 
> thanks in advance,
> 
> Roi

same

> Hi,
> 
> Nice work, thanks for shearing.
> 
> I have a problem while using the git, when running train using bash ./scripts/run_M.sh, the running stuck after printing:
> 
> train 34369 val 11425 test 11425
> 
> and remains stuck until I stop it myself.
> 
> I tried to debug it and found out the stuck happens on exp_main.py , after the command iter_count += 1.
> 
> do you have an idea why does it happen?
> 
> thanks in advance,
> 
> Roi

This is also the case when I run it. It hasn't been solved yet

**Comment by jayyounghappy** [comment]
This is also the case when I run it. It hasn't been solved yet

**Comment by tianzhou2011** [comment]
>

run the individual command in the script, which line of code caused you this stuck?

**Comment by Xjt128** [comment]
大家有懂这个反归一化的问题的吗

**Comment by tianzhou2011** [comment]
> 

data_loader.py  里面有一个scale的参数，那个是控制规划和反归一化的
