### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by yingdd0** [MAZiqing/FEDformer#44]
Hello author, thanks for sharing. When the program runs to the positional encoding part, this error is reported:

 File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\conv.py", line 307, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\conv.py", line 300, in _conv_forward
    return F.conv1d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode),
RuntimeError: Given groups=1, weight of size [512, 7, 2], expected input[32, 12, 98] to have 7 channels, but got 12 channels instead

How to solve it?

**Comment by Xjt128** [comment]
你好，关于这个fedformer模型可以交流一下吗

**Comment by jayyounghappy** [comment]
> 

你好 我也想交流一下 给个联系方式

**Comment by jayyounghappy** [comment]
> 你好，关于这个fedformer模型可以交流一下吗

我也想交流一下 有联系方式吗?

**Comment by tianzhou2011** [comment]
edit the model parameter: enc_in or enc_out if your channel size is wrong. 

> Hello author, thanks for sharing. When the program runs to the positional encoding part, this error is reported:
> 
> File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\conv.py", line 307, in forward return self._conv_forward(input, self.weight, self.bias) File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\conv.py", line 300, in _conv_forward return F.conv1d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode), RuntimeError: Given groups=1, weight of size [512, 7, 2], expected input[32, 12, 98] to have 7 channels, but got 12 channels instead
> 
> How to solve it?

**Comment by jayyounghappy** [comment]
你好,感谢你的回复,我用scripts里的单独命令运行了程序,也设置了通道数,为什么还是报错了?期望你的回复,十分感谢!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MAZiqing/FEDformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月20日(星期一) 中午11:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MAZiqing/FEDformer] RuntimeError (Issue #44)





 
edit the model parameter: enc_in or enc_out if your channel size is wrong.
  
Hello author, thanks for sharing. When the program runs to the positional encoding part, this error is reported:
 
File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\conv.py", line 307, in forward return self._conv_forward(input, self.weight, self.bias) File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\conv.py", line 300, in _conv_forward return F.conv1d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode), RuntimeError: Given groups=1, weight of size [512, 7, 2], expected input[32, 12, 98] to have 7 channels, but got 12 channels instead
 
How to solve it?
