### ISSUE TITLE
关于论文中图5里的Us(L)和Ud(L)

### ISSUE THREAD

**Issue by vaeaea** [MAZiqing/FEDformer#47]
你好，我比对了论文中的公式9和图5中关于Us(L)和Ud(L)的计算流程，请问是否在图中将Us(L)和Ud(L)标反了？
我查阅了这部分的代码，发现代码似乎是按照公式9来进行的。

**Comment by tianzhou2011** [comment]
额，是的....谢谢指正，确实好像标反了
