### ISSUE TITLE
information leakage

### ISSUE THREAD

**Issue by LCZ2815** [MAZiqing/FEDformer#48]
I would like to ask about information leakage.
Suppose I split the data into training and testing sets. Now I want to perform a decomposition operation, empirical mode decomposition or wavelet transform, or the seasonal trend decomposition method mentioned by the author, then I should only decompose the training set. If I decompose the training set and the data set together, it means that I know the future data, use the future data but still predict the future data.
What I would like to ask the author or discuss with you here is whether the many time series prediction models based on Transformer involve the defect of data leakage?

**Comment by tianzhou2011** [comment]
No, there is no data leakage here. You can simply look at the code. We use zero padding mean for the predicted signal other than its actual value before decomposition.  
![image](https://user-images.githubusercontent.com/7770939/226241505-9275f322-ea13-46e7-9cf2-6ecf456b19f7.png)

**Comment by LCZ2815** [comment]
I see, thank you for your enthusiastic answer.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月20日(星期一) 中午11:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MAZiqing/FEDformer] information leakage (Issue #48)





 
No, there is no data leakage here. You can simply look at the code. We use zero padding mean for the predicted signal other than its actual value before decomposition.
