### ISSUE TITLE
Errors for missing "use_wavelet" for running model Autoformer for baseline

### ISSUE THREAD

**Issue by FTWH** [MAZiqing/FEDformer#5]
Trying to run script:
bash scripts/run_M.sh

Errors are as follows:
`Args in experiment:
Namespace(L=3, activation='gelu', base='legendre', batch_size=32, c_out=7, checkpoints='./checkpoints/', cross_activation='tanh', d_ff=2048, d_layers=1, d_model=512, data='ETTm1', data_path='ETTm1.csv', dec_in=7, des='Exp', devices='0,1', distil=True, do_predict=False, dropout=0.05, e_layers=2, embed='timeF', enc_in=7, factor=3, features='M', freq='h', gpu=0, is_training=1, itr=3, label_len=48, learning_rate=0.0001, loss='mse', lradj='type1', mode_select='random', model='Autoformer', modes=64, moving_avg=[24], n_heads=8, num_workers=10, output_attention=False, patience=3, pred_len=96, root_path='./dataset/ETT-small/', seq_len=96, target='OT', task_id='ETTm1', train_epochs=10, use_amp=False, use_gpu=False, use_multi_gpu=False, version='Fourier')
Use CPU
Autocorrelation used !
Traceback (most recent call last):
  File "run.py", line 130, in <module>
    exp = Exp(args)  # set experiments
  File "/home/x/FEDformer/exp/exp_main.py", line 20, in __init__
    super(Exp_Main, self).__init__(args)
  File "/home/x/FEDformer/exp/exp_basic.py", line 10, in __init__
    self.model = self._build_model().to(self.device)
  File "/home/x/FEDformer/exp/exp_main.py", line 29, in _build_model
    model = model_dict[self.args.model].Model(self.args).float()
  File "/home/x/FEDformer/models/Autoformer.py", line 40, in __init__
    [
  File "/home/x/FEDformer/models/Autoformer.py", line 43, in <listcomp>
    AutoCorrelation(False, configs.factor, attention_dropout=configs.dropout,
  File "/home/x/FEDformer/layers/AutoCorrelation.py", line 35, in __init__
    self.use_wavelet = configs.wavelet
AttributeError: 'NoneType' object has no attribute 'wavelet'`

**Comment by tianzhou2011** [comment]
add a wavelet =False in the configs file should solve this. It's not in the original autoformer structure, we forget to remove it in the code......

**Comment by FTWH** [comment]
@tianzhou2011 
Thanks, actually the logic about use_wavelet is useless? Is it right? 
in line 126-128 in layers/AutoCorrelation.py (as follows) should also be removed?  Thanks!

# period-based dependencies
        if self.use_wavelet != 2:
            if self.use_wavelet == 1:
                j_list = self.j_list
                queries = queries.reshape([B, L, -1])
                keys = keys.reshape([B, L, -1])
                Ql, Qh_list = self.dwt1d(queries.transpose(1, 2))  # [B, H*D, L]
                Kl, Kh_list = self.dwt1d(keys.transpose(1, 2))
                qs = [queries.transpose(1, 2)] + Qh_list + [Ql]  # [B, H*D, L]
                ks = [keys.transpose(1, 2)] + Kh_list + [Kl]
                q_list = []
                k_list = []
                for q, k, j in zip(qs, ks, j_list):
                    q_list += [interpolate(q, scale_factor=j, mode='linear')[:, :, -L:]]
                    k_list += [interpolate(k, scale_factor=j, mode='linear')[:, :, -L:]]
                queries = torch.stack([i.reshape([B, H, E, L]) for i in q_list], dim=3).reshape([B, H, -1, L]).permute(0, 3, 1, 2)
                keys = torch.stack([i.reshape([B, H, E, L]) for i in k_list], dim=3).reshape([B, H, -1, L]).permute(0, 3, 1, 2)
            else:
                pass

**Comment by tianzhou2011** [comment]
Yes.....They are not in the original autocorrelation block, you can simply ignore them.
