### ISSUE TITLE
FourierBlock中scale的选择

### ISSUE THREAD

**Issue by rouniuyizu** [MAZiqing/FEDformer#50]
请教下scale采用这种方式的原因是什么。感谢。
https://github.com/MAZiqing/FEDformer/blob/51a51b5fdc7a1cba67b2b8ce99fcc04ddbfe0d06/layers/FourierCorrelation.py#L40

**Comment by tianzhou2011** [comment]
这个是因为传统信号傅立叶逆变换会有一个scale的1/n的系数，n是sample数，这里我们就用了这个1 / (in_channels * out_channels) 来近似这个scale
