### ISSUE TITLE
About seq_len and label_len

### ISSUE THREAD

**Issue by nevoliu** [MAZiqing/FEDformer#52]
Thank you very much for your contribution, which has been a great help to me.

I have some questions about the seq_len vs. label_len setting. Why should the label_len be smaller than the seq_len.

**Comment by Luojlong** [comment]
It seems to be a characteristic of the transformer model, assuming seq_ len=96,label_ Len=48, this label is actually the latter half of 96. The model used the latter 48 to predict the next data segment, but I don't quite remember the previous seq what it works.
