### ISSUE TITLE
关于使用自己的数据集做未来预测的问题

### ISSUE THREAD

**Issue by Luojlong** [MAZiqing/FEDformer#53]
您好，我最近在做一个关于预测未来一个月商品售量的问题，我的数据集为之前几年每日的销售量，有date，但我的预测集没有date。因此我有一些问题想向您请教一下。
1.FEDFormer在做predict的时候能否直接预测未来一个月销售量的总和值，而不是通过每日的预测来进行相加总和？
2.我做predict的时候需要使预测集生成时间戳吗，如何生成呢？（可能需要修改以下代码）
/date_provider/date_loader/def Dataset_Pre:  439行
`tmp_stamp = df_raw[['date']][border1:border2]

 tmp_stamp['date'] = pd.to_datetime(tmp_stamp.date)

 pred_dates = pd.date_range(tmp_stamp.date.values[-1], periods=self.pred_len + 1, freq=self.freq)

 df_stamp = pd.DataFrame(columns=['date'])
 df_stamp.date = list(tmp_stamp.date.values) + list(pred_dates[1:])`

**Comment by tianzhou2011** [comment]
1.我其实不是很确定直接预测会不会更好，我自己的经验，如果可以每天预测的话，单独预测以后相加是要比预测一个总和数更准的。 但你要想做的话等于在做一个单点regression的任务，你把dataloader 的Y要改一下，每一段的output都变成一个加和值就好，只是不确定这样会不会准 2. 不用生成，date是不会放进去作为特征的，date唯一的作用就是做train,val,test的数据split，你已经拆分好的话是不需要放进去的，因为这个不是我们模型的特征

**Comment by Luojlong** [comment]
谢谢，感谢您的解答。

**Comment by buer1121** [comment]
> 您好，我最近在做一个关于预测未来一个月商品售量的问题，我的数据集为之前几年每日的销售量，有date，但我的预测集没有date。因此我有一些问题想向您请教一下。 1.FEDFormer在做predict的时候能否直接预测未来一个月销售量的总和值，而不是通过每日的预测来进行相加总和？ 2.我做predict的时候需要使预测集生成时间戳吗，如何生成呢？（可能需要修改以下代码） /date_provider/date_loader/def Dataset_Pre: 439行 `tmp_stamp = df_raw[['date']][border1:border2]
> 
> tmp_stamp['date'] = pd.to_datetime(tmp_stamp.date)
> 
> pred_dates = pd.date_range(tmp_stamp.date.values[-1], periods=self.pred_len + 1, freq=self.freq)
> 
> df_stamp = pd.DataFrame(columns=['date']) df_stamp.date = list(tmp_stamp.date.values) + list(pred_dates[1:])`

你好，请问你这么做，解决了吗，我也在做类似的任务，想交流一下
