### ISSUE TITLE
modes meaning

### ISSUE THREAD

**Issue by Zero-coder** [MAZiqing/FEDformer#6]
Thanks for responding my last question,I got a new ques,if it's convenient for you to respond:
`    modes = min(modes, seq_len//2)#选取最小值不是默认的modes=64就是seq_len//2,modes
    if mode_select_method == 'random':
        index = list(range(0, seq_len // 2))#丢小数的除法，比如 5/2=2.5 5//2=2
        np.random.shuffle(index)#随机打乱index数组，也就是打乱傅里叶分量的基，为了方便后续选取随机的基，这里基也减小到了64或seq_len的一半
        index = index[:modes]
    else:
        index = list(range(0, modes))`
这里的modes意思是选取傅里叶变换的基的个数吗

**Comment by tianzhou2011** [comment]
是的，mode就是基的个数
