### ISSUE TITLE
关于Attention Map可视化

### ISSUE THREAD

**Issue by Whimmey** [MAZiqing/FEDformer#61]
作者您好，我最近在尝试修改FEDformer用作自己数据的预测。我试图输出Attention Map看看我改进效果，我设置了output_attention=True，但我发现接收到的Attens为[None.None]

我发现是下面函数中没有output_attention的判断和返回Attention的语句，请问您是如何输出像原文中那样的Attention Map的？我改添加什么代码才能做到attns的正常输出呢
https://github.com/MAZiqing/FEDformer/blob/0e28af8a03fd5971933d4b3dca6c9bc09c2a8109/layers/FourierCorrelation.py#L28
---
请问您是如何输出像原文中那样的Attention Map的？我改添加什么代码才能做到attns的正常输出呢

**Comment by tianzhou2011** [comment]
115行之后的xqk_ft 输出就好，把return None 改成return xqk_ft

**Comment by Whimmey** [comment]
感谢您的回复。像您说的那样，我在这里添加了返回xqk_ft，包括由于它在复数域而进行的傅里叶逆变换，还添加了Decoder的返回值。经过逆变换之后是一个(64,8,64,192)的张量，这里应该是分别对应了batch_size,n_head,batch_size,pred_len。感觉和需要的map不太对应，如果要输出n_head张图的话，每张图需要的数据应该是(seq_len,seq_len)吧？还请解答一下


https://github.com/MAZiqing/FEDformer/blob/0e28af8a03fd5971933d4b3dca6c9bc09c2a8109/layers/FourierCorrelation.py#L125

**Comment by tianzhou2011** [comment]
不是啊，64，64分别是两个hidden吧，怎么可能有两个batch_size; 每张图所需要的数据就是hidden * hidden，
我们这个是频域attention， 整条线通过projection映射为每个频域的系数表征，只有单点attention才是seq_len*seq_len

**Comment by Whimmey** [comment]
是我之前写错了，不好意思。就是说这个张量形状为(modes,n_head,modes,pred_len)，modes参数也就是我们定义的供随机选择的mode的总数对吗？然后热力图也就是模型对这些mode的注意力？
我基于傅里叶逆变换处理后得到的数据绘制的map长这样的。算是完成了嘛

![)GA4O~3%)}8P9L3OP4U%@G2](https://github.com/MAZiqing/FEDformer/assets/46125181/4a1d1c7d-36df-438f-aabe-16e5626a0403)

**Comment by tianzhou2011** [comment]
嗯，还可以换换activation function ,记得attention 用tanh或者softmax画出来的图差挺多的，但end2end performance却差不多

**Comment by Whimmey** [comment]
非常感谢您的解答 受益良多
