### ISSUE TITLE
FEA-f 中\quat V的问题

### ISSUE THREAD

**Issue by Xiangyi-Sufe** [MAZiqing/FEDformer#62]
您好，请问在FED-f中，公式7中有\quat V，但是在FourierCrossAttention module的第118行，并不是与\quat V相乘，是书写问题吗？

**Comment by Xiangyi-Sufe** [comment]
还有，FourierCrossAttention module的第119行，有个layer层，好像并没有在论文的FEA-f这一块写出来，请问这个layer层的意义是什么

**Comment by tianzhou2011** [comment]
1. 是的，QKV 我们把Q和V合并了，设计的时候用的是QKV,但后面发现用Q K训练稳定一点，就没改，但其实差不多，你改成正常用QKV是一样的 2. 这是个learnable kernel，就是文章figure3 里面那个蓝色的R， 就为了增加表征能力
