### ISSUE TITLE
双卡运行bug

### ISSUE THREAD

**Issue by qaqxk** [MAZiqing/FEDformer#63]
RuntimeError: einsum(): the number of subscripts in the equation (3) does not match the number of dimensions (4) for operand 0 and no ellipsis was given请问双卡运行会有维度错误要怎么解决呢

**Comment by tianzhou2011** [comment]
确实多卡会遇到问题，einops有些操作似乎不支持多卡。 先用单卡跑吧，时间也不久，我们当时没处理这个问题，就全是用单卡跑的

**Comment by kingkingyoutiao** [comment]
self.weights1 = nn.Parameter(
            self.scale * torch.rand(8, in_channels // 8, out_channels // 8, len(self.index), 2 , dtype=torch.float))
    def compl_mul1d(self, input, weights):
        weights=torch.complex(weights[..., 0],weights[..., 1])
        return torch.einsum("bhi,hio->bho", input, weights)
大佬您好，近期我在多卡训练的时候也遇到了相关问题，请问在其定义时就额外增加一个维度存储实部虚部，到其运算时再构造复数参与einsum，这样是否可行呢？（这样暂时可以跑通，我不确定这样的weights梯度算出来正常吗？）

**Comment by kingkingyoutiao** [comment]
> 确实多卡会遇到问题，einops有些操作好像不支持多卡。先用单卡跑吧，时间也很快，我们当时没处理这个问题，就全部是用单卡跑的

kingkingyoutiao评论了 现在
[金金油条](https://github.com/kingkingyoutiao)
[现在](https://github.com/MAZiqing/FEDformer/issues/63#issuecomment-2660582870)
self.weights1 = nn.Parameter(
self.scale * torch.rand(8, in_channels // 8, out_channels // 8, len(self.index), 2 , dtype=torch.float))
def compl_mul1d(self, input, Weights):
Weights=torch.complex(weights[..., 0],weights[..., 1])
return torch.einsum("bhi,hio->bho", input, Weights)
大佬您好，最近我在多卡训练的时候也遇到了相关问题，请问在其时就额外增加一个维度的存储实部虚部，到其装甲时再构造复数参与einsum，这样是否可以解决呢？（这样暂时可以跑通，我不确定这样的权重算出来正常吗？）
