### ISSUE TITLE
TypeError: Adam.__init__() missing 1 required positional argument: 'params'

### ISSUE THREAD

**Issue by Med-Rokaimi** [MAZiqing/FEDformer#64]
TypeError                                 Traceback (most recent call last)
[<ipython-input-23-02d64f1c3641>](https://localhost:8080/#) in <cell line: 10>()
      8 enc_seq_len = 7 # supposing you want the model to base its forecasts on the previous 7 days of data
      9 
---> 10 optimizer = torch.optim.Adam()
     11 
     12 criterion = torch.nn.MSELoss()

TypeError: Adam.__init__() missing 1 required positional argument: 'params'

**Comment by tianzhou2011** [comment]
which version of Torch you are using? install the appropriate version as per the requirements mentioned in the requirements.txt file

**Comment by Med-Rokaimi** [comment]
Thank you for reply. Fixed.
