### ISSUE TITLE
Can't get the ideal result in table2(FEDformer-w for ILI24pl)

### ISSUE THREAD

**Issue by GiaoBruce** [MAZiqing/FEDformer#65]
Thanks for your marvelous work FEDformer, recently I have trained the model, but I didn't get the result in your paper(table2 FEDformer-w ILI24), here are my testing results for it:

![results](https://github.com/MAZiqing/FEDformer/assets/56425466/30a03e69-61be-4434-b3a1-0426bb595a71)

These results are obviously different with table2 MSE 2.203 MAE 0.963 

The args used are shown below：
and batch_size is 32
![VLBP{3 ETC9_109{XTY`HIH](https://github.com/MAZiqing/FEDformer/assets/56425466/63101192-7838-4294-b2aa-31688738f0cc)

I have no idea about it(I am a beginner in NLP), could you give me some help，Thanks in advance.  d :)

**Comment by tianzhou2011** [comment]
![image](https://github.com/MAZiqing/FEDformer/assets/7770939/85448f84-5329-4d88-b636-ff3e026a90fb)
![image](https://github.com/MAZiqing/FEDformer/assets/7770939/249f20fc-3f02-4c06-ad3d-9b684560d8b9)
it might take a while for parameter tuning, but you will get the result. PS ILI is not a good benchmark. It's too volatile.

**Comment by GiaoBruce** [comment]
Thank you for your generous help! Good Night.  :)
