### ISSUE TITLE
Output the attention weights of the model

### ISSUE THREAD

**Issue by MatthiasNeumueller** [MAZiqing/FEDformer#66]
I have a question related to the #61. In that issue, it is mentioned that in order to output the attention weights, you have to replace None with xqk_ft in the FourierCrossAttention class. At least, that class forward function is the only one where I could find that variable. https://github.com/MAZiqing/FEDformer/blob/0e28af8a03fd5971933d4b3dca6c9bc09c2a8109/layers/FourierCorrelation.py#L65

However, after closer inspection, I noticed that the attns variable within the FEDformer.py forward function is only connected to the FourierBlock class and has nothing to do with the FourierCrossAttention class. I also tried out to make the proposed changes from the above issue and nothing happens. The only change that has an effect on the attns variable in the FEDformer forward function is if I change the None value within the forward function of the FourierBlock class.

As a consequence, I would like to ask if you could clarify a bit more on the necessary changes in order to get the output_attention values?

**Comment by tianzhou2011** [comment]
Sorry for replying late. I missed this issue.  I am not sure what you mean by "nothing happens." Nothing will happen about forecasting, the output of the attention weight is just for visualization. It's just an intermediate result.
