### ISSUE TITLE
forecast result

### ISSUE THREAD

**Issue by anranlovelife** [MAZiqing/FEDformer#67]
作者您好，您的项目对我来说非常有帮助，感谢您们。但是我现在遇到一个麻烦，在训练是数据是不是仅仅标准化了，但是没有反标准化，如果想恢复原本的数据 ，我该如何做呢？非常期待你的回复！

**Comment by tianzhou2011** [comment]
dataloader里面有个inverse_transform，用那个函数返回来就好
