### ISSUE TITLE
train epochs

### ISSUE THREAD

**Issue by jayyounghappy** [MAZiqing/FEDformer#68]
你好，我是一个研0入门，在复现代码时我遇到一个问题，为什么我将train epochs改为30，但是运行时还没有到30轮就提前结束了？
我是用的这条运行命令：python -u run.py --is_training 1 --root_path ./dataset/ETT-small/ --data_path ETTm1.csv --task_id ETTm1 --model FEDformer --data ETTm1 --features S --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3  --enc_in 1 --dec_in 1 --c_out 1 --des 'Exp' --d_model 512 --itr 3 --train_epochs=30

如果我想获得一个0-30轮MSE和MAE的收敛变化，应该怎么做?
期待你的回答。

**Comment by tianzhou2011** [comment]
里面default了early stop， 你要不想它可能提前终止，把early stop设成train epochs数就好
