### ISSUE TITLE
关于masked attention的疑问

### ISSUE THREAD

**Issue by sunxiaoyao-git** [MAZiqing/FEDformer#69]
您好！
      我在看了论文和代码后，有个关于掩码的疑问。原始transformer里面decode部分的self-attention有mask，但我看您代码里面貌似没有，是因为填充了序列后不需要掩码了吗？

**Comment by tianzhou2011** [comment]
NLP的transformer是autoregressive生成的，fedformer是一步生成的，decoder不需要mask

**Comment by sunxiaoyao-git** [comment]
谢谢您的回复~
