### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by wbxibcy** [MAZiqing/FEDformer#71]
RuntimeError: Given groups=1, weight of size [512, 7, 3], expected input[32, 1, 98] to have 7 channels, but got 1 channels instead
why ?

**Comment by tianzhou2011** [comment]
Could you please clarify which script you're running? I'm not certain what it is you're referring to.

**Comment by jannichorst** [comment]
Providing the parameters would definitely help to answer the question but to make a wild guess, have you set the ---features parameter to  'S'? Because I think you might input multivariate data while using the univariate mode. Just a guess though.
