### ISSUE TITLE
关于exp_main.py中的一个错误

### ISSUE THREAD

**Issue by superguymj** [MAZiqing/FEDformer#72]
如果--features为MS，exp_main.py的训练、验证以及预测都没有对模型预测输出取target列。

**Comment by tianzhou2011** [comment]
抱歉，我们并没有跑过任何MS的实验，文章里也没有report过，这个实验设置只是开始想着可能要做，放在代码里的，最后没写这部分。如果你要做MS的实验的话要自己写一下这部分代码。

**Comment by FAFUuser** [comment]
> 如果--features为MS，exp_main.py的训练、验证以及预测都没有对模型预测输出取target列。

您好，请问你这部分实现了吗？如果修改的话，可以直接在模型输出outputs的基础上取最后一列吗？
即：
outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)   
outputs = outputs [:, :, -1:].to(self.device)

**Comment by FAFUuser** [comment]
> 如果--features为MS，exp_main.py的训练、验证以及预测都没有对模型预测输出取target列。

您好，再向你请教一个问题，就是MS相比较于S，会不会提高模型预测OT的精度，OT是同一个值。也就是通过添加与OT相关的特征，能否提高模型对于OT的预测精度？

**Comment by tianzhou2011** [comment]
会提升的，MS比S的效果要更好一些，channel 维度还是有信息能提高的
