### ISSUE TITLE
关于模型参数量的问题

### ISSUE THREAD

**Issue by nihaoya12** [MAZiqing/FEDformer#82]
我尝试调整了频率选择的mode选项，在相同输入长度下尝试了不同的频率选择的长度，但发现不同频率长度下的模型参数量和flops是相同的，请问大家有遇到过这种情况吗？知道这是为什么吗？
使用的是thop库中的profile函数

**Comment by tianzhou2011** [comment]
设断点到R的那个weight上看吧，不同mode number R的weight大小会随之改变的。这个package我也不确定他怎么算的
