### ISSUE TITLE
Train FEDformer with wavelets

### ISSUE THREAD

**Issue by philipperbd** [MAZiqing/FEDformer#83]
I'm just starting to discover the code (really nice work btw). 

I struggle to find how to perform FEDformer training with wavelets instead of Fourier.  Could someone help me? Thanks

**Comment by tianzhou2011** [comment]
parser.add_argument('--version', type=str, default='Fourier',
                        help='for FEDformer, there are two versions to choose, options: [Fourier, Wavelets]')

change this setting to Wavelets
