### ISSUE TITLE
为什么FourierCrossAttention的代码没有用到v呢

### ISSUE THREAD

**Issue by wiluen** [MAZiqing/FEDformer#84]
xqk_ft = (torch.einsum("bhex,bhey->bhxy", xq_ft_, xk_ft_))貌似计算了qk
xqkv_ft = torch.einsum("bhxy,bhey->bhex", xqk_ft, xk_ft_)  怎么又乘了k
v没用到呀

**Comment by efg001** [comment]
https://github.com/MAZiqing/FEDformer/issues/62

**Comment by tianzhou2011** [comment]
感谢上面的同学，看之前issue就好
